# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.CharField(max_length=1024),
        ),
    ]
