# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170417_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='lessons',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
