# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170417_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='regular',
            field=models.BooleanField(default=True),
        ),
    ]
